blank_issues_enabled: false
contact_links:
  - name: TANGI Discord Community
    url: https://discord.gg/tangi
    about: Join our Discord community for quick questions and discussions
  - name: TANGI Marketing Team Email
    url: mailto:marketing@tangi.io
    about: Contact the marketing team directly for urgent matters
